CVPrioritize/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    url(r'^portal/',include('Recruiter_HM.urls')),
    url(r'^',include('candidate.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT,})]

Recruiter_HM/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^logout', views.logout_view, name="logout_view"),
    url(r'^dashboard',views.dashboard,name="dashboard"),
   
    url(r'^job_post_details$',views.job_post_details,name="job_post_details"),
    #url(r'^match',views.match,name="match"),
  
   
  
    url(r'^specific_post/(?P<id>(\d+))/',views.specific_post,name="specific_post"),
    url(r'^edit_jd/(?P<id>(\d+))/',views.edit_jd,name="edit_jd"),
    url(r'^publish_jd/(?P<id>(\d+))/',views.publish_jd,name="publish_jd"),
    url(r'^show_jd/(?P<id>(\d+))/',views.show_jd,name="show_jd"),
    
    url(r'^$',views.signin,name="signin"),
    url(r'^success_jd/(?P<id>(\d+))/',views.success_jd,name="success_jd"),
    url(r'^unsuccess_jd/(?P<id>(\d+))/',views.unsuccess_jd,name="unsuccess_jd"),

    url(r'^job_post$',views.job_post,name="job_post"),   
   
]   

candidate/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = "home"),
    url(r'^editdetails/(\d+)/', views.editdetails, name='editdetails'),
]

Recruiter_HM/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.core.validators import MinLengthValidator


EXPERIENCE_CHOICES = (
    ('0-2','0-2'),
    ('3-5','3-5'),
    ('6-8','6-8'),
    ('9-12','9-12'),
    ('13-15','13-15'),
    ('15+','15+')
)

class JobPost(models.Model):
    title= models.CharField(max_length=100,validators=[MinLengthValidator(3)])
    responsibilities = models.TextField(max_length=2000,validators=[MinLengthValidator(30)])
    qualification = models.CharField(max_length=2000,validators = [MinLengthValidator(2)])
    additional_qualification = models.CharField(max_length=2000,null=True,blank=True,validators = [MinLengthValidator(2)])
    overall_experience = models.CharField(max_length=6, choices=EXPERIENCE_CHOICES, default='0-2')
    primary_skills=models.CharField(max_length=30,validators=[MinLengthValidator(1)])
    secondary_skills=models.CharField(max_length=30,null=True,blank=True,validators=[MinLengthValidator(1)])
    tertiary_skills=models.CharField(max_length=30,null=True,blank=True,validators=[MinLengthValidator(1)])
    status=models.IntegerField()
    team= models.CharField(max_length=100,validators=[MinLengthValidator(3)])
    people=models.IntegerField()
    created_timestamp=models.DateTimeField(null=True,blank=True)
    updated_timestamp=models.DateTimeField(null=True, blank=True)
    deleted_timestamp=models.DateTimeField(null=True, blank=True)

    def __int__(self):
        return self.id
    


class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    AID=models.CharField(max_length=7,validators=[MinLengthValidator(7)])
    role=models.CharField(max_length=17,validators=[MinLengthValidator(9)])
    updated_timestamp=models.DateTimeField(null=True, blank=True)





    

Recruiter_HM/forms.py
from django import forms
from .models import JobPost



class LoginForm(forms.Form):
    AID=forms.CharField(min_length=7,max_length=7,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'AID'}))
    Password=forms.CharField(min_length=8,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
   


class ChangePassword(forms.Form):
    
    Old_Password=forms.CharField(min_length=8,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Old Password'}))
    New_Password=forms.CharField(min_length=8,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'New Password'}))
    Confirm_Password=forms.CharField(min_length=8,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm New Password'}))

    def clean(self):
        cleaned_data=super().clean()
        Old_Password=cleaned_data.get('Old_Password')
        New_Password=cleaned_data.get('New_Password')
        Confirm_Password=cleaned_data.get('Confirm_Password')
        if New_Password!=Confirm_Password:
            raise forms.ValidationError('Password Does Not Matach')


class ForgetPassword(forms.Form):
    use_required_attribute=False
    New_Password=forms.CharField(min_length=8,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'New Password'}))
    Confirm_Password=forms.CharField(min_length=8,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Confirm New Password'}))
    
    
    def clean(self):
        cleaned_data=super().clean()
        New_Password=cleaned_data.get('New_Password')
        Confirm_Password=cleaned_data.get('Confirm_Password')
        if New_Password!=Confirm_Password:
            raise forms.ValidationError('Password Does Not Matach')

class JobPostForm(forms.ModelForm):
    status = forms.IntegerField(widget=forms.HiddenInput(),label='')
    primary_skills=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter skills separted by comma'}))
    # tertiary_skills=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter skills separted by comma'}))
    # secondary_skills=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter skills separted by comma'}))


    class Meta:
        model=JobPost
        fields=['title','responsibilities','qualification','additional_qualification','team','people','overall_experience','primary_skills','secondary_skills','tertiary_skills','status']
    
    def __init__(self, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
      
        

class Candidate(forms.Form):
    use_required_attribute=False
    Name=forms.CharField(min_length=4,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Name'}))
    Email=forms.EmailField(min_length=4,widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Email'}))
    Contact=forms.CharField(min_length=10,max_length=10,widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Phone Number'}))
    Address=forms.CharField(min_length=20,max_length=2000,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Address'}))
    Pin=forms.CharField(min_length=6,max_length=6,widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'PIN'}))
    Experience=forms.CharField(min_length=1,max_length=2,widget=forms.NumberInput(attrs={'class':'form-control','placeholder':'Experience'}))
    Qualifiction=forms.CharField(min_length=20,max_length=2000,widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Qualification'}))
  

Recruiter_HM/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect,render_to_response
from django.http import HttpResponseRedirect
from django.urls import reverse
from candidate.models import Candidate,Application
from .forms import JobPostForm,LoginForm
from .models import JobPost,Profile
from django import forms
from itertools import chain
from django.utils import timezone
from taggit.models import Tag
from django.core import serializers
import json
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout


@login_required
def show_jd(request,id):
    job=JobPost.objects.get(pk=id)
    job_status=JobPost.objects.get(pk=id)
    print(job_status.status)
    if(job_status.status == 3):
        main_list=job.application_set.filter(score__gt=80).order_by('-score')
        print(main_list)

        return render(request,'show_jd.html',{'main_list':main_list})

    else:
        return render(request,'show_jd.html',{'messages': 'This Job Post Has Been Closed'})

    



@login_required
def job_post(request):
    if request.method=="POST":
         access=request.session.get('access')
         form=JobPostForm(request.POST)
         if form.is_valid():
             tags= [i.lower().strip() for i in request.POST['primary_skills'].split(',')]
             sec_tags = [ i.lower().strip() for i in request.POST['secondary_skills'].split(',')]
             tert_tags = [ i.lower().strip() for i in request.POST['tertiary_skills'].split(',')]
             for i in range(len(tags)):
                if(tags[i] in sec_tags ):
                    return render(request,'job_post.html',{'form':form,'messages':'You cant have same primary and secondary skills'})
                    
                if(tags[i] in tert_tags):
                    return render(request,'job_post.html',{'form':form,'messages':'You cant have same primary and tertiary skills'})
             u=form.save(commit=False)
             u.created_timestamp=timezone.now()
             u.save()
             form.save_m2m()
             request.session['access']=access
             return redirect("/portal/dashboard")
         else:
             return render(request,'job_post.html',{'form':form,'messages':'The Minimum Length for title is 3 characters,for Qualification field is 30 characters and for responsibilities field is 30 characters'})

             
    form=JobPostForm() 
    return render(request,'job_post.html',{'form':form})



@login_required
def job_post_details(request):
    k1=''
    k2=''
    k3=''
    k4=''
    k5=''
    k6=''
    status=request.GET.get('status')
    stat = status.split(',')
    print(stat)
    stats=[]
    access=request.session.get('access')
    if len(stat)==1:
        for i in range(len(stat)):
            val=int(stat[i])
            stats.append(val)
    else:
        for i in range(len(stat)-1):
            val = int(stat[i])
            stats.append(val)
    print(stats)


    if(status == '6'):
        jobs=JobPost.objects.all()
    else:
        jobs=JobPost.objects.filter(status__in=stats)
        for i in range(len(stats)):
            if(stats[i] == 0):
                k1="checked"
            elif(stats[i] == 1):
                k2="checked"
            elif(stats[i] == 2):
                k3="checked"
            elif(stats[i] == 3):
                k4="checked"
            elif(stats[i] == 4):
                k5="checked"
            elif(stats[i] == 5):
                k6="checked"
        else:
            pass
        
    if access=="Hiring Manager":
        data_dict={'status':status,'access':access,'jobs':jobs,'Received':'Received','Requested':'Requested','k1':k1,'k2':k2,'k3':k3,'k4':k4,'k5':k5,'k6':k6}
    else:
        data_dict={'status':status,'access':access,'jobs':jobs,'Received':'Sent','Requested':'Pending','k2':k2,'k3':k3,'k4':k4,'k5':k5,'k6':k6}
    return render(request,'job_post_list.html',data_dict)
 



@login_required
def specific_post(request,id):
    access=request.session.get('access')
    u=JobPost.objects.get(id=id)
    return render(request,'specific_job_post.html',{'job':u,'access':access})




@login_required
def publish_jd(request,id):
    job=JobPost.objects.get(id=id)
    job.status=3
    job.save()
    return redirect("/portal/dashboard")




@login_required
def success_jd(request,id):
    job=JobPost.objects.get(id=id)
    job.status=4
    job.deleted_timestamp=timezone.now()
    job.save()
    return redirect("/portal/dashboard")



@login_required
def unsuccess_jd(request,id):
    job=JobPost.objects.get(id=id)
    job.status=5 
    job.deleted_timestamp=timezone.now()
    job.save()
    return redirect("/portal/dashboard")




def match():
    jm=JobPost.objects.all()
    data = serializers.serialize('json',jm)
    return data
     
  




@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("signin"))



@login_required
def edit_jd(request,id):
    access=request.session.get('access')
    if(request.method== "POST"):
        form=JobPostForm(request.POST)
        if form.is_valid():
            job=JobPost.objects.get(id=id)
            id=job.id
            
            create=job.created_timestamp
            job.delete()
            tags= [i.lower().strip() for i in request.POST['primary_skills'].split(',')]
            sec_tags = [ i.lower().strip() for i in request.POST['secondary_skills'].split(',')]
            tert_tags = [ i.lower().strip() for i in request.POST['tertiary_skills'].split(',')]
            for i in range(len(tags)):
                if(tags[i] in sec_tags ):
                    return render(request,'job_post.html',{'form':form,'messages':'You cant have same primary and secondary skills'})
                    
                if(tags[i] in tert_tags):
                    return render(request,'job_post.html',{'form':form,'messages':'You cant have same primary and tertiary skills'})
            u=form.save(commit=False)
            u.id=id
            u.created_timestamp=create
            u.updated_timestamp=timezone.now()
            u.save()
            form.save_m2m()
            request.session['access']=access
            return redirect("/portal/dashboard")

        else:
            print(form.errors)
            return render(request,'edit_jd.html',{'form':form,'messages':'The Minimum Length for title is 3 characters,for Qualification field is 30 characters and for responsibilities field is 30 characters'})
        
    
    job=JobPost.objects.get(id=id)
    
    initial={'title':job.title,'responsibilities':job.responsibilities,'qualification':job.qualification,'additional_qualification':job.additional_qualification,'overall_experience': job.overall_experience,'primary_skills':job.primary_skills,'secondary_skills':job.secondary_skills,'tertiary_skills':job.tertiary_skills,'team':job.team,'people':job.people}
    form=JobPostForm(initial)
    return render(request,'edit_jd.html',{'form':form,'access':access,'id':id})





@login_required
def dashboard(request):
    jobs=JobPost.objects.all()
    if jobs:
        if request.session.get('access')=='Hiring Manager':
            access=request.session.get('access')
            try:
                recieved_count=JobPost.objects.filter(status=2).count()
            except JobPost.DoesNotExist:
                recieved_count=0
            try:
                requested_count=JobPost.objects.filter(status=1).count()
            except JobPost.DoesNotExist:
                requested_count=0
            
            try:
                published_count=JobPost.objects.filter(status=3).count()
            except JobPost.DoesNotExist:
                published_count=0

            request.session['access'] = access
            specific=list(JobPost.objects.all().values_list('id'))
            specific=list(chain(*specific))
            print(specific)

            titles=list(JobPost.objects.all().values_list('title'))
            titles=list(chain(*titles))
            
            print(titles)
            categories = list() 
            succesful_closed = list()
            published = list()
            for ti in titles:
                categories.append(ti)  
            for spec in specific:
                try:
                    c=JobPost.objects.filter(id=spec).filter(status=3).count()
                    published.append(c)
                    

                except JobPost.DoesNotExist:
                    c=0
                    published.append(c)
            
                try:
                    c1=JobPost.objects.filter(id=spec).filter(status=4).count()
                    succesful_closed.append(c1)
                    

                except JobPost.DoesNotExist:
                    c1=0
                    succesful_closed.append(c1)  
              
                

            data_dict = {'re_c': recieved_count,'req_c':requested_count,'pub_c':published_count,'Received':'Recieved','Requested':'Requested','Published':'Published','access':access,  'categories': json.dumps(categories),
        'succesful_closed': json.dumps(succesful_closed),
        'published': json.dumps(published)}
            
        else:
             access=request.session.get('access')
             try:
                 recieved_count=JobPost.objects.filter(status=2).count()
             except JobPost.DoesNotExist:
                 recieved_count=0

             try:
                 requested_count=JobPost.objects.filter(status=1).count()
             except JobPost.DoesNotExist:
                 requested_count=0
             
             try:
                 published_count=JobPost.objects.filter(status=3).count()
             except JobPost.DoesNotExist:
                 published_count=0
             request.session['access'] = access

             titles=list(JobPost.objects.all().values_list('title'))
             titles=list(chain(*titles))

Recruiter_HM/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Fidelity | Application Portal</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Lato" />
    <style>
        * {
            box-sizing: border-box;
        }
        body {
            max-width: 100%;
            font-family: Lato;
            margin: 0px;
        }
    </style>
   
</head>
<body style="overflow-x:hidden">
    <header class="navbar m-0" style="background-color:#BA0C00;min-height:9vh">
        <div class="container-fluid">
            <div class="navbar-header">
                    <a href="{% url 'home' %}"><div class="navbar-brand text-white"><h2 class="h2">Fidelity</h2></div></a>     
            </div>
        </div>
    </header>
    {% block content%}
    {% endblock %}
   
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" 
    crossorigin="anonymous"></script>

    {% block extra_js %}
    {% endblock %}

    </body>
</html>

Recruiter_HM/templates/edit_jd.html
{% extends 'base.html' %}

{% block content%}
<script>
        function formSubmit(status) {
            $("#id_status").val(status)
            $("#form").submit();
        }
    </script>
<div class="container p-3">
        {% if access == "Hiring Manager" %}
        <h1>Create Job Post</h1>
        {% elif access == "Recruiter" %}
        <h1>Give Instructions</h1>
        {% endif %}
    <form method="POST">
        {% csrf_token %}
        {% if messages %}
        <div>{{ messages }}</div>
        {% endif %}
        {% for field in form %}
            <div class="row w-100">
                <div class="form-group w-100">
                    <div class="col-sm-2 mb-2 text-right float-left">{{field.label}}</div>
                    <div class="col-sm-10 float-right">
                        {{field}}
                        {% for error in field.errors %}
                            <div class="text-danger">{{error}}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}

                    {% if access == "Hiring Manager" %}
                    <button type="submit" class="btn btn-success" onclick="formSubmit(1)">Submit</button>
                    {% elif access == "Recruiter"  %}
                    <button type="submit" class="btn btn-success" onclick="formSubmit(2)">Send Back</button>
                    {% endif %}

                </form>
            </div>
            
            {% endblock %}

Recruiter_HM/templates/job_post.html
{% extends 'base.html' %}

{% block content%}
<script>
        function formSubmit(status) {
            $("#id_status").val(status)
            $("#form").submit();
        }
    </script>
<div class="container p-3">
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="row w-100">
                <div class="form-group w-100">
                    <div class="col-sm-2 mb-2 text-right float-left">{{field.label}}</div>
                    <div class="col-sm-10 float-right">
                        {{field}}
                        {% for error in field.errors %}
                            <div class="text-danger">{{error}}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if messages %}
            <div class="text-danger">{{ messages }}</div>
        {% endif %}
                    
                    <button type="submit" class="btn btn-success" onclick="formSubmit(0)">Save</button>
                    
                    
                    <button type="submit" class="btn btn-success" onclick="formSubmit(1)">Submit</button>
                    
                </form>
            </div>
            
            {% endblock %}

Recruiter_HM/templates/login.html
{% extends 'base.html' %}

{% block content%}
   <div class="container p-3">
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="row w-100">
                <div class="form-group w-100">
                    <div class="col-sm-2 mb-2 text-right float-left">{{field.label}}</div>
                    <div class="col-sm-10 float-right">
                        {{field}}
                        {% for error in field.errors %}
                            <div class="text-danger">{{error}}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if messages %}
            <div class="text-danger">{{ messages }}</div>
        {% endif %}
                    <button class="btn btn-success">Login</button>
                </form>
            </div>
            
            {% endblock %}

Recruiter_HM/templates/show_jd.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
<!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  


</head>
<body>


<div>

        <div class="container-fluid">
            
            <div class="row">
              <div class="row" style="background-color:#bce8f1">
                <div class="col-sm-6" st></div>
                <div  class="col-sm-6"><a href='{% url 'logout_view' %}' style="float:right"><inputbutton type="submit" class="btn btn-fail">logout</a></div>
            </div>
            </div>
            <div class="row">
              {% if messages %}
              <h2>{{messages}}</h2>
            </div>
            {% else %}
   
             <div class="row">
   
   
               <div class="col-sm-12">
                   <h2>Prioritized List of Candidates</h2>
                       <p>Filter list by any parameter</p>
               <input class="form-control" id="myInput" type="text" placeholder="Search..">
               <br>
               </div>
             </div>
   
   
   
   
               <div class="col-sm-10">
                  <table class="table table-bordered">
                       <thead class="table-primary" style="background-color:#a2afc8">
                           <tr>
                               <th>Serial No.</th>
                               <th>Resume ID</th>
                               <th>Job_ID</th>
                               <th>Name</th>
                               <th>Score</th>
                               <th>CV</th>
                           </tr>
               </thead>
               <tbody id="myTable">
               {% for li in main_list %}
               <tr>
               <td>{{ forloop.counter }}</td>
               <td>{{ li.candidateid.id }}</td>
               <td>{{ li.jobid.id }}</td>
               <td>{{li.candidateid.name}}</td>
               <td>{{li.score}}</td>
               <td><a href="{{li.candidateid.cv_path.url}}" target="_blank"><i class="fa fa-link" aria-hidden="true"></i></a></td>
{#               <td><a href="{{li.cv_path}}" target="_blank">{{li.cv_path}}</a></td>#}
               </tr>
               {% endfor %}
           </tbody>
           </table>
               </div>
               </div>
             </div>
   
   
   
               <div class="container-fluid">
                   <ul class="pagination justify-content-center">
                   <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                   <li class="page-item"><a class="page-link" href="#">1</a></li>
                   <li class="page-item"><a class="page-link" href="#">2</a></li>
                   <li class="page-item"><a class="page-link" href="#">3</a></li>
                   <li class="page-item"><a class="page-link" href="#">Next</a></li>
                   </ul>
               </div>
     </div>
   
   
       <script>
                   $(document).ready(function(){
                   $("#myInput").on("keyup", function() {
                   var value = $(this).val().toLowerCase();
                   $("#myTable tr").filter(function() {
                   $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                   });
                   });
                   });
           </script>
   
         </div>
   {% endif %}
     </div>
   <br><br>
   
   </div>

</body>
</html>